### ISSUE TITLE
Add to conda-forge

### ISSUE THREAD

**Issue by iuryt** [circstat/pycircstat#73]
Nice package, have you already considered to put it in conda-forge?

**Comment by hoechenberger** [comment]
Hello, I've created a package and PyCircStat should now be available from conda-forge.

**Comment by philippberens** [comment]
Thanks so much - any help with maintenance is highly appreciated, I just don't find the time.

**Comment by iuryt** [comment]
Let me know if I can be of any help.

**Comment by hoechenberger** [comment]
> Do you have any interesting instructions I could read to learn how to co-maintain it?

Sure, there's extensive documentation at https://conda-forge.org/docs/maintainer/updating_pkgs.html

But since there's a bot that automatically detects new releases on PyPI and updates the feedstock automatically, normally the only reason to manually intervene is to update the list of dependencies if they've changed!

>I can test and update the installation instructions, but basically once it's available in conda-forge, it should be something like `conda install -c conda-forge pycircstat` or `mamba install -c conda-forge pycircstat` , right? 

Absolutely!

> How you usually run the unittests?

You mean on `conda-forge`? You don't :) The tests we run there are very simple, e.g. just trying to `import` the package and that's usually it.

**Comment by hoechenberger** [comment]
I've opened a request to add you as a co-maintainer, however the bot hasn't picked this up yet:
https://github.com/conda-forge/pycircstat-feedstock/issues/3
